name: logistics
description: A new Flutter application.

# The following line prevents the package from being accidentally published to     sdk: ">=2.7.0 <3.0.0"
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.0  
  signature: ^5.5.0
  dio: ^5.7.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: 
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.0
  provider: ^6.0.1
  geocode:
  permission_handler: ^10.4.1
  galli_map: ^1.2.3
  galli_vector_plugin: ^0.0.9
  





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/edit.png
    - assets/images/phone.png
    - assets/images/email.png
    - assets/images/path.png
    - assets/images/arrowdown.png
    - assets/images/plus.png
    - assets/images/withcode.png
    - assets/images/activeqricon.png
    - assets/images/background_image.png
    - assets/images/logo.png
    - assets/images/middivider.png
    - assets/images/splash_logo.png
    - assets/images/qricon.png
    - assets/images/active_withcode.png
    - assets/images/cancel.png
    - assets/images/receiverpath.png
    - assets/images/active_path.png
    - assets/images/dark_path.png
  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Regular.ttf
           weight: 400
         - asset: fonts/Roboto-Bold.ttf
           weight: 700
         - asset: fonts/Roboto-Medium.ttf
           weight: 500


  

  





